name: Pre-Merge Checks

on:
  pull_request:
    branches:
        - "**"
        - "!main"
        - "!staging"


jobs:
  pre-merge-checks:
    name: Pre-Merge Checks
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
        #   pip install -r requirements.txt
          pip install flake8 black

      - name: Lint Code with flake8
        run: |
          flake8 .
        continue-on-error: false

      - name: Format Code with autopep8
        run: |
          black --check .
      
      - name: Run Unit Test on test_entrypoint.py
        run: |
          python -m unittest test_entrypoint.py
      
      - name: Security Check with Bandit
        uses: owasp/dependency-check-action@v4
        with:
          output_directory: './reports'
        continue-on-error: true  # Optional, will not block the PR if there are warnings

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: pre-merge-reports
          path: ./reports
